//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyTracker.Manager.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChineseSimplified {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChineseSimplified() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyTracker.Manager.Langs.ChineseSimplified", typeof(ChineseSimplified).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加  的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币数 的本地化字符串。
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量图表  的本地化字符串。
        /// </summary>
        internal static string AmountGraph {
            get {
                return ResourceManager.GetString("AmountGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [时间 - 数量] 的本地化字符串。
        /// </summary>
        internal static string AmountGraph1 {
            get {
                return ResourceManager.GetString("AmountGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总体变化率:  的本地化字符串。
        /// </summary>
        internal static string AmountGraph2 {
            get {
                return ResourceManager.GetString("AmountGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新变化率:  的本地化字符串。
        /// </summary>
        internal static string AmountGraph3 {
            get {
                return ResourceManager.GetString("AmountGraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 本图表主要反映时间变化下货币数量发生的变化 的本地化字符串。
        /// </summary>
        internal static string AmountGraph4 {
            get {
                return ResourceManager.GetString("AmountGraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收支 的本地化字符串。
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收支筛选 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterEnabled {
            get {
                return ResourceManager.GetString("ChangeFilterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅显示收支 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterLabel {
            get {
                return ResourceManager.GetString("ChangeFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的记录 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterValueLabel {
            get {
                return ResourceManager.GetString("ChangeFilterValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收支图表  的本地化字符串。
        /// </summary>
        internal static string ChangeGraph {
            get {
                return ResourceManager.GetString("ChangeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [时间 - 收支] 的本地化字符串。
        /// </summary>
        internal static string ChangeGraph1 {
            get {
                return ResourceManager.GetString("ChangeGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 本图表主要反映时间变化下货币收支量的变化 的本地化字符串。
        /// </summary>
        internal static string ChangeGraph2 {
            get {
                return ResourceManager.GetString("ChangeGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (上升中) 的本地化字符串。
        /// </summary>
        internal static string ChangeRateToolTip {
            get {
                return ResourceManager.GetString("ChangeRateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (下降中) 的本地化字符串。
        /// </summary>
        internal static string ChangeRateToolTip1 {
            get {
                return ResourceManager.GetString("ChangeRateToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收支文本染色 的本地化字符串。
        /// </summary>
        internal static string ChangeTextColoring {
            get {
                return ResourceManager.GetString("ChangeTextColoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试清除当前选中货币下的所有异常记录
        /// 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前判断标准: 收支等于总金额的记录 / 收支为 0 的记录
        /// 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp1 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除了  的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp2 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  条异常记录。 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp3 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除异常记录 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsLabel {
            get {
                return ResourceManager.GetString("ClearExTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按时间聚类 的本地化字符串。
        /// </summary>
        internal static string ClusterByTime {
            get {
                return ResourceManager.GetString("ClusterByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置: 以 的本地化字符串。
        /// </summary>
        internal static string ClusterByTimeHelp1 {
            get {
                return ResourceManager.GetString("ClusterByTimeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 为间隔显示数据 的本地化字符串。
        /// </summary>
        internal static string ClusterByTimeHelp2 {
            get {
                return ResourceManager.GetString("ClusterByTimeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        internal static string ClusterInterval {
            get {
                return ResourceManager.GetString("ClusterInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选排序选项 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel {
            get {
                return ResourceManager.GetString("ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录选项 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel1 {
            get {
                return ResourceManager.GetString("ConfigLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel2 {
            get {
                return ResourceManager.GetString("ConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击以展开/收回 的本地化字符串。
        /// </summary>
        internal static string ConfigLabelHelp {
            get {
                return ResourceManager.GetString("ConfigLabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制 的本地化字符串。
        /// </summary>
        internal static string CopyTransactionsHelp {
            get {
                return ResourceManager.GetString("CopyTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录至剪贴板 的本地化字符串。
        /// </summary>
        internal static string CopyTransactionsHelp1 {
            get {
                return ResourceManager.GetString("CopyTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置 的本地化字符串。
        /// </summary>
        internal static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注:
        ///1.插件预设的19种货币不可删除，只可以隐藏
        ///2.不建议对非货币物品进行追踪, 建议使用其他插件来追踪非货币物品
        ///3.删除货币并不会删除已有的数据文件，如有需要请自行删除 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败: 货币已存在 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp1 {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败: 货币不存在 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp2 {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义货币追踪 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyLabel {
            get {
                return ResourceManager.GetString("CustomCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义货币追踪 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyLabel1 {
            get {
                return ResourceManager.GetString("CustomCurrencyLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前选择: 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyLabel2 {
            get {
                return ResourceManager.GetString("CustomCurrencyLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择... 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyLabel3 {
            get {
                return ResourceManager.GetString("CustomCurrencyLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索框 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyLabel4 {
            get {
                return ResourceManager.GetString("CustomCurrencyLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除  的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第  的本地化字符串。
        /// </summary>
        internal static string Di {
            get {
                return ResourceManager.GetString("Di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (单位: 千) 的本地化字符串。
        /// </summary>
        internal static string DividedName {
            get {
                return ResourceManager.GetString("DividedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (单位: 百万) 的本地化字符串。
        /// </summary>
        internal static string DividedName1 {
            get {
                return ResourceManager.GetString("DividedName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (单位: 十亿) 的本地化字符串。
        /// </summary>
        internal static string DividedName2 {
            get {
                return ResourceManager.GetString("DividedName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 [测试] 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 Enter 键确认 的本地化字符串。
        /// </summary>
        internal static string EditHelp {
            get {
                return ResourceManager.GetString("EditHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入修改后的地点名称 的本地化字符串。
        /// </summary>
        internal static string EditHelp1 {
            get {
                return ResourceManager.GetString("EditHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已修改 的本地化字符串。
        /// </summary>
        internal static string EditHelp2 {
            get {
                return ResourceManager.GetString("EditHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录的地名为: 的本地化字符串。
        /// </summary>
        internal static string EditHelp3 {
            get {
                return ResourceManager.GetString("EditHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出为CSV 的本地化字符串。
        /// </summary>
        internal static string ExportCsv {
            get {
                return ResourceManager.GetString("ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前货币下无收支记录 的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage1 {
            get {
                return ResourceManager.GetString("ExportCsvMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间,货币数,收支,地点 的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage2 {
            get {
                return ResourceManager.GetString("ExportCsvMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导出CSV文件至:  的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage3 {
            get {
                return ResourceManager.GetString("ExportCsvMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注1: 为避免错误，请勿输入过长的文件名
        ///注2: 导出的数据将会应用当前所启用的一切排序筛选条件(不包含分页) 的本地化字符串。
        /// </summary>
        internal static string FileRenameHelp {
            get {
                return ResourceManager.GetString("FileRenameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果留空，文件名则为:  的本地化字符串。
        /// </summary>
        internal static string FileRenameHelp1 {
            get {
                return ResourceManager.GetString("FileRenameHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入文件名: (按Enter键确认) 的本地化字符串。
        /// </summary>
        internal static string FileRenameLabel {
            get {
                return ResourceManager.GetString("FileRenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名:  的本地化字符串。
        /// </summary>
        internal static string FileRenameLabel1 {
            get {
                return ResourceManager.GetString("FileRenameLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前时间 的本地化字符串。
        /// </summary>
        internal static string FileRenameLabel2 {
            get {
                return ResourceManager.GetString("FileRenameLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间筛选 的本地化字符串。
        /// </summary>
        internal static string FilterByTime {
            get {
                return ResourceManager.GetString("FilterByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共  的本地化字符串。
        /// </summary>
        internal static string Gong {
            get {
                return ResourceManager.GetString("Gong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明帮助 的本地化字符串。
        /// </summary>
        internal static string GraphHelpMessages {
            get {
                return ResourceManager.GetString("GraphHelpMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 建议在主界面启用各类筛选器，减少记录数量
        ///- 可以通过点击图表的横轴或纵轴使图表界面自适应显示
        ///- 本界面仍处于测试阶段，如果遇到任何 BUG 或有对新功能的想法，请提交 ISSUE 的本地化字符串。
        /// </summary>
        internal static string GraphHelpMessages1 {
            get {
                return ResourceManager.GetString("GraphHelpMessages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录数量: 的本地化字符串。
        /// </summary>
        internal static string GraphLabel {
            get {
                return ResourceManager.GetString("GraphLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表 的本地化字符串。
        /// </summary>
        internal static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        internal static string Greater {
            get {
                return ResourceManager.GetString("Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 (双击右键) 的本地化字符串。
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        internal static string InverseSelect {
            get {
                return ResourceManager.GetString("InverseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点 的本地化字符串。
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点收支图表  的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph {
            get {
                return ResourceManager.GetString("LocationAmountGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   [地点 - 收支] 的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph1 {
            get {
                return ResourceManager.GetString("LocationAmountGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 本图表主要反映该货币记录中各地点下所产生收支的总额 的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph2 {
            get {
                return ResourceManager.GetString("LocationAmountGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点筛选 的本地化字符串。
        /// </summary>
        internal static string LocationFilter {
            get {
                return ResourceManager.GetString("LocationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点图表 的本地化字符串。
        /// </summary>
        internal static string LocationGraph {
            get {
                return ResourceManager.GetString("LocationGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   [地点 - 地点频次] 的本地化字符串。
        /// </summary>
        internal static string LocationGraph1 {
            get {
                return ResourceManager.GetString("LocationGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 本图表主要反映该货币记录中各地点的出现频次 的本地化字符串。
        /// </summary>
        internal static string LocationGraph2 {
            get {
                return ResourceManager.GetString("LocationGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并 的本地化字符串。
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入临界值 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并了  的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp1 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  条记录。 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp2 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并当前选中货币下，地点相同、彼此相邻且收支 小于 临界值的记录。
        ///合并后记录的数量、时间将会取最新一条记录的数据，收支则会取被合并的各记录之和。
        ///如果临界值为 0，则会合并一切地点相同、彼此相邻的记录。
        ///
        ///单向合并: 正负数改变量的记录分开计算相邻与合并
        ///双向合并：正负数改变量的记录一起计算相邻与合并
        /// 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp3 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选择 2 条记录 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp4 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并记录 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临界值 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel1 {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双向合并 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel2 {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单项合并 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel3 {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动合并 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel4 {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小记录值 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValue {
            get {
                return ResourceManager.GetString("MinimumRecordValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置:
        ///副本内: 当货币收支的绝对值≥  的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ,
        ///副本外: 当货币收支的绝对值≥  的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp1 {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  时，
        ///才进行一次数据记录
        ///注: 可能造成不准确的地点记录 / 副本完成时，无论当前改变量是否到达临界值，都会进行一次记录 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp2 {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本内最小记录值:  的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本外最小记录值:  的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel1 {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用更改 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel2 {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负收支 的本地化字符串。
        /// </summary>
        internal static string NegativeChange {
            get {
                return ResourceManager.GetString("NegativeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未选中任何记录 的本地化字符串。
        /// </summary>
        internal static string NoTransactionsSelected {
            get {
                return ResourceManager.GetString("NoTransactionsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 的本地化字符串。
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开数据文件夹 的本地化字符串。
        /// </summary>
        internal static string OpenDataFolder {
            get {
                return ResourceManager.GetString("OpenDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有隐藏货币均已还原 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp {
            get {
                return ResourceManager.GetString("OrderChangeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已还原 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp1 {
            get {
                return ResourceManager.GetString("OrderChangeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 种货币 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp2 {
            get {
                return ResourceManager.GetString("OrderChangeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前位置: 的本地化字符串。
        /// </summary>
        internal static string OrderChangeLabel {
            get {
                return ResourceManager.GetString("OrderChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 (双击右键) 的本地化字符串。
        /// </summary>
        internal static string OrderChangeLabel1 {
            get {
                return ResourceManager.GetString("OrderChangeLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  页 的本地化字符串。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正收支 的本地化字符串。
        /// </summary>
        internal static string PositiveChange {
            get {
                return ResourceManager.GetString("PositiveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒序排序 的本地化字符串。
        /// </summary>
        internal static string ReverseSort {
            get {
                return ResourceManager.GetString("ReverseSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅显示 的本地化字符串。
        /// </summary>
        internal static string TimeFilterLabel {
            get {
                return ResourceManager.GetString("TimeFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  至  的本地化字符串。
        /// </summary>
        internal static string TimeFilterLabel1 {
            get {
                return ResourceManager.GetString("TimeFilterLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期间的记录 的本地化字符串。
        /// </summary>
        internal static string TimeFilterLabel2 {
            get {
                return ResourceManager.GetString("TimeFilterLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录副本内数据 的本地化字符串。
        /// </summary>
        internal static string TrackInDuty {
            get {
                return ResourceManager.GetString("TrackInDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分副本、特殊场景探索中会给予货币奖励
        ///插件默认当玩家在副本、特殊场景探索中时暂停记录，等待玩家退出它们时再计算期间货币的总增减，无法记录副本内货币变化的地点
        ///你可以通过开启本项目关闭此功能
        ///
        ///注: 这可能会使插件记录大量小额数据，使得记录量大幅增加，但可以正常记录副本内货币变化的地点 的本地化字符串。
        /// </summary>
        internal static string TrackInDutyHelp {
            get {
                return ResourceManager.GetString("TrackInDutyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时器模式:
        ///每隔  的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp {
            get {
                return ResourceManager.GetString("TrackModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  毫秒，检查一次所有货币的变化情况 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp1 {
            get {
                return ResourceManager.GetString("TrackModeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息模式:
        ///每当接收到特定的新消息时，检查一次所有货币的变化情况
        ///(此模式下可能会得到更加精准的记录)
        ///
        ///注：如果发现任何不记录的情况，请附上场景向我提交 ISSUE！ 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp2 {
            get {
                return ResourceManager.GetString("TrackModeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过低的触发间隔会带来更高的性能损耗 (不明显) 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp3 {
            get {
                return ResourceManager.GetString("TrackModeHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录模式 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel {
            get {
                return ResourceManager.GetString("TrackModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时器模式 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel1 {
            get {
                return ResourceManager.GetString("TrackModeLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息模式 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel2 {
            get {
                return ResourceManager.GetString("TrackModeLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔 (ms) 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel3 {
            get {
                return ResourceManager.GetString("TrackModeLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录 的本地化字符串。
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到符合条件的记录。 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp {
            get {
                return ResourceManager.GetString("TransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未选择任何货币类型。 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp1 {
            get {
                return ResourceManager.GetString("TransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注: 操作无法回退，如有需要，请做好数据备份 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp2 {
            get {
                return ResourceManager.GetString("TransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单页记录数: 的本地化字符串。
        /// </summary>
        internal static string TransactionsPerPage {
            get {
                return ResourceManager.GetString("TransactionsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的货币类型 的本地化字符串。
        /// </summary>
        internal static string UnknownCurrency {
            get {
                return ResourceManager.GetString("UnknownCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知区域 的本地化字符串。
        /// </summary>
        internal static string UnknownLocation {
            get {
                return ResourceManager.GetString("UnknownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选中 的本地化字符串。
        /// </summary>
        internal static string Unselect {
            get {
                return ResourceManager.GetString("Unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
