//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyTracker.Manager.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChineseSimplified {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChineseSimplified() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyTracker.Manager.Langs.ChineseSimplified", typeof(ChineseSimplified).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加  的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币数 的本地化字符串。
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量图表  的本地化字符串。
        /// </summary>
        internal static string AmountGraph {
            get {
                return ResourceManager.GetString("AmountGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [时间 - 数量] 的本地化字符串。
        /// </summary>
        internal static string AmountGraph1 {
            get {
                return ResourceManager.GetString("AmountGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总体变化率 的本地化字符串。
        /// </summary>
        internal static string AmountGraph2 {
            get {
                return ResourceManager.GetString("AmountGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新变化率 的本地化字符串。
        /// </summary>
        internal static string AmountGraph3 {
            get {
                return ResourceManager.GetString("AmountGraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 本图表主要反映时间变化下货币数量发生的变化 的本地化字符串。
        /// </summary>
        internal static string AmountGraph4 {
            get {
                return ResourceManager.GetString("AmountGraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收支 的本地化字符串。
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收支筛选 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterEnabled {
            get {
                return ResourceManager.GetString("ChangeFilterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅显示收支 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterLabel {
            get {
                return ResourceManager.GetString("ChangeFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的记录 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterValueLabel {
            get {
                return ResourceManager.GetString("ChangeFilterValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收支图表  的本地化字符串。
        /// </summary>
        internal static string ChangeGraph {
            get {
                return ResourceManager.GetString("ChangeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [时间 - 收支] 的本地化字符串。
        /// </summary>
        internal static string ChangeGraph1 {
            get {
                return ResourceManager.GetString("ChangeGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 本图表主要反映时间变化下货币收支量的变化 的本地化字符串。
        /// </summary>
        internal static string ChangeGraph2 {
            get {
                return ResourceManager.GetString("ChangeGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (上升中) 的本地化字符串。
        /// </summary>
        internal static string ChangeRateToolTip {
            get {
                return ResourceManager.GetString("ChangeRateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (下降中) 的本地化字符串。
        /// </summary>
        internal static string ChangeRateToolTip1 {
            get {
                return ResourceManager.GetString("ChangeRateToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收支文本染色 的本地化字符串。
        /// </summary>
        internal static string ChangeTextColoring {
            get {
                return ResourceManager.GetString("ChangeTextColoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试清除当前选中货币下的所有异常记录
        /// 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前判断标准: 收支等于总金额的记录 / 收支为 0 的记录
        /// 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp1 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除了  的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp2 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  条异常记录。 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp3 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除异常记录 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsLabel {
            get {
                return ResourceManager.GetString("ClearExTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按时间聚类 的本地化字符串。
        /// </summary>
        internal static string ClusterByTime {
            get {
                return ResourceManager.GetString("ClusterByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以 的本地化字符串。
        /// </summary>
        internal static string ClusterByTimeHelp1 {
            get {
                return ResourceManager.GetString("ClusterByTimeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 为间隔显示数据 的本地化字符串。
        /// </summary>
        internal static string ClusterByTimeHelp2 {
            get {
                return ResourceManager.GetString("ClusterByTimeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        internal static string ClusterInterval {
            get {
                return ResourceManager.GetString("ClusterInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示列 的本地化字符串。
        /// </summary>
        internal static string ColumnsDisplayed {
            get {
                return ResourceManager.GetString("ColumnsDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开插件主界面 的本地化字符串。
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /ct &lt;货币名&gt; → 打开指定货币的数据界面 的本地化字符串。
        /// </summary>
        internal static string CommandHelp1 {
            get {
                return ResourceManager.GetString("CommandHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选排序选项 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel {
            get {
                return ResourceManager.GetString("ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录选项 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel1 {
            get {
                return ResourceManager.GetString("ConfigLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel2 {
            get {
                return ResourceManager.GetString("ConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击以展开/收回 的本地化字符串。
        /// </summary>
        internal static string ConfigLabelHelp {
            get {
                return ResourceManager.GetString("ConfigLabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制 的本地化字符串。
        /// </summary>
        internal static string CopyTransactionsHelp {
            get {
                return ResourceManager.GetString("CopyTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录至剪贴板 的本地化字符串。
        /// </summary>
        internal static string CopyTransactionsHelp1 {
            get {
                return ResourceManager.GetString("CopyTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置 的本地化字符串。
        /// </summary>
        internal static string Current_Settings {
            get {
                return ResourceManager.GetString("Current Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置 的本地化字符串。
        /// </summary>
        internal static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注:
        ///1.插件预设的3种货币不可删除，只可以隐藏
        ///2.不建议对非货币物品进行追踪, 建议使用其他插件来追踪非货币物品
        ///3.删除货币并不会删除已有的数据文件，如有需要请自行删除 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败: 货币已存在 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp1 {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败: 货币不存在 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp2 {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义货币追踪 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyTracker {
            get {
                return ResourceManager.GetString("CustomCurrencyTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除  的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第  的本地化字符串。
        /// </summary>
        internal static string Di {
            get {
                return ResourceManager.GetString("Di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (单位: 十亿) 的本地化字符串。
        /// </summary>
        internal static string DividedUnitBil {
            get {
                return ResourceManager.GetString("DividedUnitBil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (单位: 百万) 的本地化字符串。
        /// </summary>
        internal static string DividedUnitMil {
            get {
                return ResourceManager.GetString("DividedUnitMil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (单位: 千) 的本地化字符串。
        /// </summary>
        internal static string DividedUnitThou {
            get {
                return ResourceManager.GetString("DividedUnitThou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑失败 的本地化字符串。
        /// </summary>
        internal static string EditFailed {
            get {
                return ResourceManager.GetString("EditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 Enter 键确认 的本地化字符串。
        /// </summary>
        internal static string EditHelp {
            get {
                return ResourceManager.GetString("EditHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入修改后的地点名称 的本地化字符串。
        /// </summary>
        internal static string EditHelp1 {
            get {
                return ResourceManager.GetString("EditHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已修改 的本地化字符串。
        /// </summary>
        internal static string EditHelp2 {
            get {
                return ResourceManager.GetString("EditHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录的地名为 的本地化字符串。
        /// </summary>
        internal static string EditHelp3 {
            get {
                return ResourceManager.GetString("EditHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录的备注为 的本地化字符串。
        /// </summary>
        internal static string EditHelp4 {
            get {
                return ResourceManager.GetString("EditHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出为CSV 的本地化字符串。
        /// </summary>
        internal static string ExportCsv {
            get {
                return ResourceManager.GetString("ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前货币下无收支记录 的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage1 {
            get {
                return ResourceManager.GetString("ExportCsvMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间,货币数,收支,地点,备注 的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage2 {
            get {
                return ResourceManager.GetString("ExportCsvMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导出CSV文件至:  的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage3 {
            get {
                return ResourceManager.GetString("ExportCsvMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注: 此处的导出文件类型选择同样会影响其他地方的导出文件格式 的本地化字符串。
        /// </summary>
        internal static string ExportFileHelp {
            get {
                return ResourceManager.GetString("ExportFileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注: 导出的数据将会应用当前所启用的一切排序筛选条件(不包含分页) 的本地化字符串。
        /// </summary>
        internal static string ExportFileHelp1 {
            get {
                return ResourceManager.GetString("ExportFileHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的文件导出类型 的本地化字符串。
        /// </summary>
        internal static string ExportFileHelp2 {
            get {
                return ResourceManager.GetString("ExportFileHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # 货币数据导出 - 的本地化字符串。
        /// </summary>
        internal static string ExportFileMDHeader {
            get {
                return ResourceManager.GetString("ExportFileMDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 | 时间 | 货币数 | 收支 | 地点 | 备注 |
        ///| --- | --- | --- | --- | --- | 的本地化字符串。
        /// </summary>
        internal static string ExportFileMDHeader1 {
            get {
                return ResourceManager.GetString("ExportFileMDHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出文件类型 的本地化字符串。
        /// </summary>
        internal static string ExportFileType {
            get {
                return ResourceManager.GetString("ExportFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果留空，文件名则为:  的本地化字符串。
        /// </summary>
        internal static string FileRenameHelp1 {
            get {
                return ResourceManager.GetString("FileRenameHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名: (按 Enter 键确认) 的本地化字符串。
        /// </summary>
        internal static string FileRenameLabel {
            get {
                return ResourceManager.GetString("FileRenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前时间 的本地化字符串。
        /// </summary>
        internal static string FileRenameLabel2 {
            get {
                return ResourceManager.GetString("FileRenameLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间筛选 的本地化字符串。
        /// </summary>
        internal static string FilterByTime {
            get {
                return ResourceManager.GetString("FilterByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来自 的本地化字符串。
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金碟 的本地化字符串。
        /// </summary>
        internal static string GoldSaucer {
            get {
                return ResourceManager.GetString("GoldSaucer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共  的本地化字符串。
        /// </summary>
        internal static string Gong {
            get {
                return ResourceManager.GetString("Gong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明帮助 的本地化字符串。
        /// </summary>
        internal static string GraphHelpMessages {
            get {
                return ResourceManager.GetString("GraphHelpMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 建议在主界面启用各类筛选器，减少记录数量
        ///- 可以通过点击图表的横轴或纵轴使图表界面自适应显示
        ///- 本界面仍处于测试阶段，如果遇到任何 BUG 或有对新功能的想法，请提交 ISSUE 的本地化字符串。
        /// </summary>
        internal static string GraphHelpMessages1 {
            get {
                return ResourceManager.GetString("GraphHelpMessages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录数量: 的本地化字符串。
        /// </summary>
        internal static string GraphLabel {
            get {
                return ResourceManager.GetString("GraphLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表 的本地化字符串。
        /// </summary>
        internal static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        internal static string Greater {
            get {
                return ResourceManager.GetString("Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指南 的本地化字符串。
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮忙翻译 的本地化字符串。
        /// </summary>
        internal static string HelpTranslate {
            get {
                return ResourceManager.GetString("HelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诚挚感谢你的付出 的本地化字符串。
        /// </summary>
        internal static string HelpTranslateHelp {
            get {
                return ResourceManager.GetString("HelpTranslateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 (双击右键) 的本地化字符串。
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        internal static string InverseSelect {
            get {
                return ResourceManager.GetString("InverseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点 的本地化字符串。
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点收支图表  的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph {
            get {
                return ResourceManager.GetString("LocationAmountGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [地点 - 收支] 的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph1 {
            get {
                return ResourceManager.GetString("LocationAmountGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 本图表主要反映该货币记录中各地点下所产生收支的总额 的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph2 {
            get {
                return ResourceManager.GetString("LocationAmountGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点筛选 的本地化字符串。
        /// </summary>
        internal static string LocationFilter {
            get {
                return ResourceManager.GetString("LocationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点图表 的本地化字符串。
        /// </summary>
        internal static string LocationGraph {
            get {
                return ResourceManager.GetString("LocationGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [地点 - 地点频次] 的本地化字符串。
        /// </summary>
        internal static string LocationGraph1 {
            get {
                return ResourceManager.GetString("LocationGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 本图表主要反映该货币记录中各地点的出现频次 的本地化字符串。
        /// </summary>
        internal static string LocationGraph2 {
            get {
                return ResourceManager.GetString("LocationGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并 的本地化字符串。
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由 的本地化字符串。
        /// </summary>
        internal static string MergedSpecificHelp {
            get {
                return ResourceManager.GetString("MergedSpecificHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录合并而成 的本地化字符串。
        /// </summary>
        internal static string MergedSpecificHelp1 {
            get {
                return ResourceManager.GetString("MergedSpecificHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果此项留空,
        ///合并后记录的 备注 部分则为:
        ///(由 X 条记录合并而成) 的本地化字符串。
        /// </summary>
        internal static string MergeNoteHelp {
            get {
                return ResourceManager.GetString("MergeNoteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入临界值 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并了  的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp1 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  条记录。 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp2 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并当前选中货币下，地点相同、彼此相邻且收支 小于 临界值的记录。
        ///合并后记录的数量、时间将会取最新一条记录的数据，收支则会取被合并的各记录之和。
        ///如果临界值为 0，则会合并一切地点相同、彼此相邻的记录。
        ///
        ///单向合并: 正负数改变量的记录分开计算相邻与合并
        ///双向合并：正负数改变量的记录一起计算相邻与合并
        /// 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp3 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选择 2 条记录 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp4 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并记录 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动合并 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel4 {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仙人微彩 的本地化字符串。
        /// </summary>
        internal static string MiniCactpot {
            get {
                return ResourceManager.GetString("MiniCactpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小记录值 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValue {
            get {
                return ResourceManager.GetString("MinimumRecordValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本内:
        ///当货币收支的绝对值≥  的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本外:
        ///当货币收支的绝对值≥  的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp1 {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时才进行一次数据记录
        ///
        ///注:
        ///1.根据你设定的值，可能造成不准确的位置记录
        ///2.当你离开副本区域时，无论目前发生改变的货币的具体收支是否达到了你所设定的临界值，
        ///都会进行一次记录
        ///   所以，如果你想要“一个副本一条记录”的效果，把 副本内最小记录值 设置的高点就行    (比如给金币设置个 10万 的临界值) 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp2 {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本内最小记录值:  的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本外最小记录值:  的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel1 {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用更改 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel2 {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要帮助 的本地化字符串。
        /// </summary>
        internal static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负收支 的本地化字符串。
        /// </summary>
        internal static string NegativeChange {
            get {
                return ResourceManager.GetString("NegativeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未选中任何记录 的本地化字符串。
        /// </summary>
        internal static string NoTransactionsSelected {
            get {
                return ResourceManager.GetString("NoTransactionsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 的本地化字符串。
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单项合并 的本地化字符串。
        /// </summary>
        internal static string OneWayMerge {
            get {
                return ResourceManager.GetString("OneWayMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开数据文件夹 的本地化字符串。
        /// </summary>
        internal static string OpenDataFolder {
            get {
                return ResourceManager.GetString("OpenDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作指南 的本地化字符串。
        /// </summary>
        internal static string OperationGuide {
            get {
                return ResourceManager.GetString("OperationGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有隐藏货币均已还原 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp {
            get {
                return ResourceManager.GetString("OrderChangeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已还原 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp1 {
            get {
                return ResourceManager.GetString("OrderChangeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 种货币 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp2 {
            get {
                return ResourceManager.GetString("OrderChangeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前位置: 的本地化字符串。
        /// </summary>
        internal static string OrderChangeLabel {
            get {
                return ResourceManager.GetString("OrderChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主世界 的本地化字符串。
        /// </summary>
        internal static string Overworld {
            get {
                return ResourceManager.GetString("Overworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  页 的本地化字符串。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索... 的本地化字符串。
        /// </summary>
        internal static string PleaseSearch {
            get {
                return ResourceManager.GetString("PleaseSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择... 的本地化字符串。
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正收支 的本地化字符串。
        /// </summary>
        internal static string PositiveChange {
            get {
                return ResourceManager.GetString("PositiveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录副本名称 的本地化字符串。
        /// </summary>
        internal static string RecordContentName {
            get {
                return ResourceManager.GetString("RecordContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含副本与PVP 的本地化字符串。
        /// </summary>
        internal static string RecordContentNameHelp {
            get {
                return ResourceManager.GetString("RecordContentNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下面的选项仅代表勾选后相关记录的备注部分会被填入其来源
        ///
        ///如: (来自 九宫幻卡)  的本地化字符串。
        /// </summary>
        internal static string RecordGoldSaucerHelp {
            get {
                return ResourceManager.GetString("RecordGoldSaucerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录仙人微彩 的本地化字符串。
        /// </summary>
        internal static string RecordMiniCactpot {
            get {
                return ResourceManager.GetString("RecordMiniCactpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录设置 的本地化字符串。
        /// </summary>
        internal static string RecordSettings {
            get {
                return ResourceManager.GetString("RecordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录传送费 的本地化字符串。
        /// </summary>
        internal static string RecordTPCosts {
            get {
                return ResourceManager.GetString("RecordTPCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送费包含金币以及传送网使用券 的本地化字符串。
        /// </summary>
        internal static string RecordTPCostsHelp {
            get {
                return ResourceManager.GetString("RecordTPCostsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录传送目的地 的本地化字符串。
        /// </summary>
        internal static string RecordTPDest {
            get {
                return ResourceManager.GetString("RecordTPDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录九宫幻卡 的本地化字符串。
        /// </summary>
        internal static string RecordTripleTriad {
            get {
                return ResourceManager.GetString("RecordTripleTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原
        ///(双击右键) 的本地化字符串。
        /// </summary>
        internal static string RestoreHidden {
            get {
                return ResourceManager.GetString("RestoreHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒序排序 的本地化字符串。
        /// </summary>
        internal static string ReverseSort {
            get {
                return ResourceManager.GetString("ReverseSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议或反馈 的本地化字符串。
        /// </summary>
        internal static string SuggestOrReport {
            get {
                return ResourceManager.GetString("SuggestOrReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格外观 的本地化字符串。
        /// </summary>
        internal static string TableAppearance {
            get {
                return ResourceManager.GetString("TableAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送至 的本地化字符串。
        /// </summary>
        internal static string TeleportTo {
            get {
                return ResourceManager.GetString("TeleportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图内传送 的本地化字符串。
        /// </summary>
        internal static string TeleportWithinArea {
            get {
                return ResourceManager.GetString("TeleportWithinArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临界值 的本地化字符串。
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录副本内数据 的本地化字符串。
        /// </summary>
        internal static string TrackInDuty {
            get {
                return ResourceManager.GetString("TrackInDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果未勾选本项，当你位于副本区域内时，插件将会暂停记录所有货币可能发生的任何变化，直至你离开副本，这也同时会导致地点记录不准确。
        ///
        ///推荐同时配置 最小记录值 功能。 的本地化字符串。
        /// </summary>
        internal static string TrackInDutyHelp {
            get {
                return ResourceManager.GetString("TrackInDutyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时器模式:
        ///每隔 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp {
            get {
                return ResourceManager.GetString("TrackModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毫秒，检查一次所有货币的变化情况 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp1 {
            get {
                return ResourceManager.GetString("TrackModeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息模式:
        ///每当接收到特定的新消息时，检查一次所有货币的变化情况
        ///(此模式下会得到更加精准的记录)
        ///
        ///注：如果发现任何不记录的情况，请附上场景向我提交 ISSUE！ 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp2 {
            get {
                return ResourceManager.GetString("TrackModeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过低的触发间隔会带来更高的性能损耗 (不明显) 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp3 {
            get {
                return ResourceManager.GetString("TrackModeHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录模式 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel {
            get {
                return ResourceManager.GetString("TrackModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时器模式 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel1 {
            get {
                return ResourceManager.GetString("TrackModeLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息模式 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel2 {
            get {
                return ResourceManager.GetString("TrackModeLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔 (ms) 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel3 {
            get {
                return ResourceManager.GetString("TrackModeLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录 的本地化字符串。
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到符合条件的记录。 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp {
            get {
                return ResourceManager.GetString("TransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未选择任何货币类型。 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp1 {
            get {
                return ResourceManager.GetString("TransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注: 操作无法回退，如有需要，请做好数据备份 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp2 {
            get {
                return ResourceManager.GetString("TransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单页记录数: 的本地化字符串。
        /// </summary>
        internal static string TransactionsPerPage {
            get {
                return ResourceManager.GetString("TransactionsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 九宫幻卡 的本地化字符串。
        /// </summary>
        internal static string TripleTriad {
            get {
                return ResourceManager.GetString("TripleTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双向合并 的本地化字符串。
        /// </summary>
        internal static string TwoWayMerge {
            get {
                return ResourceManager.GetString("TwoWayMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知副本 的本地化字符串。
        /// </summary>
        internal static string UnknownContent {
            get {
                return ResourceManager.GetString("UnknownContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的货币类型 的本地化字符串。
        /// </summary>
        internal static string UnknownCurrency {
            get {
                return ResourceManager.GetString("UnknownCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知区域 的本地化字符串。
        /// </summary>
        internal static string UnknownLocation {
            get {
                return ResourceManager.GetString("UnknownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选中 的本地化字符串。
        /// </summary>
        internal static string Unselect {
            get {
                return ResourceManager.GetString("Unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待交易完成 的本地化字符串。
        /// </summary>
        internal static string WaitExchange {
            get {
                return ResourceManager.GetString("WaitExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果选中此项，则当你使用系统商店、市场布告板、雇员/部队箱或军队筹备时，会等待交换结束，再检查所有货币的增减情况 的本地化字符串。
        /// </summary>
        internal static string WaitExchangeHelp {
            get {
                return ResourceManager.GetString("WaitExchangeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日, 一, 二, 三, 四, 五, 六 的本地化字符串。
        /// </summary>
        internal static string WeekDays {
            get {
                return ResourceManager.GetString("WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
