//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyTracker.Manager.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyTracker.Manager.Langs.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add  的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount 的本地化字符串。
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount Graph  的本地化字符串。
        /// </summary>
        internal static string AmountGraph {
            get {
                return ResourceManager.GetString("AmountGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Time - Amount] 的本地化字符串。
        /// </summary>
        internal static string AmountGraph1 {
            get {
                return ResourceManager.GetString("AmountGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overall Rate 的本地化字符串。
        /// </summary>
        internal static string AmountGraph2 {
            get {
                return ResourceManager.GetString("AmountGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest Rate 的本地化字符串。
        /// </summary>
        internal static string AmountGraph3 {
            get {
                return ResourceManager.GetString("AmountGraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * This plot mainly reflects changes in the Amount of the currency over Time. 的本地化字符串。
        /// </summary>
        internal static string AmountGraph4 {
            get {
                return ResourceManager.GetString("AmountGraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Filter 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterEnabled {
            get {
                return ResourceManager.GetString("ChangeFilterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only display transactions 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterLabel {
            get {
                return ResourceManager.GetString("ChangeFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 in Change 的本地化字符串。
        /// </summary>
        internal static string ChangeFilterValueLabel {
            get {
                return ResourceManager.GetString("ChangeFilterValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Graph 的本地化字符串。
        /// </summary>
        internal static string ChangeGraph {
            get {
                return ResourceManager.GetString("ChangeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Time - Change] 的本地化字符串。
        /// </summary>
        internal static string ChangeGraph1 {
            get {
                return ResourceManager.GetString("ChangeGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * This plot mainly reflects changes in the Change of the currency over Time. 的本地化字符串。
        /// </summary>
        internal static string ChangeGraph2 {
            get {
                return ResourceManager.GetString("ChangeGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Increasing) 的本地化字符串。
        /// </summary>
        internal static string ChangeRateToolTip {
            get {
                return ResourceManager.GetString("ChangeRateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Decreasing) 的本地化字符串。
        /// </summary>
        internal static string ChangeRateToolTip1 {
            get {
                return ResourceManager.GetString("ChangeRateToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Text Coloring 的本地化字符串。
        /// </summary>
        internal static string ChangeTextColoring {
            get {
                return ResourceManager.GetString("ChangeTextColoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempt to clear all exception transactions under the currently selected currency
        /// 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current judgment criteria:
        ///Transactions with Change equal to the Amount /with Change equal to 0
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp1 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed  的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp2 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  exception transactions. 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsHelp3 {
            get {
                return ResourceManager.GetString("ClearExTransactionsHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Ex 的本地化字符串。
        /// </summary>
        internal static string ClearExTransactionsLabel {
            get {
                return ResourceManager.GetString("ClearExTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cluster By Time 的本地化字符串。
        /// </summary>
        internal static string ClusterByTime {
            get {
                return ResourceManager.GetString("ClusterByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display transactions in 的本地化字符串。
        /// </summary>
        internal static string ClusterByTimeHelp1 {
            get {
                return ResourceManager.GetString("ClusterByTimeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hour(s) interval 的本地化字符串。
        /// </summary>
        internal static string ClusterByTimeHelp2 {
            get {
                return ResourceManager.GetString("ClusterByTimeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hours 的本地化字符串。
        /// </summary>
        internal static string ClusterInterval {
            get {
                return ResourceManager.GetString("ClusterInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filiter Options 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel {
            get {
                return ResourceManager.GetString("ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record Options 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel1 {
            get {
                return ResourceManager.GetString("ConfigLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        internal static string ConfigLabel2 {
            get {
                return ResourceManager.GetString("ConfigLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to expand/collapse 的本地化字符串。
        /// </summary>
        internal static string ConfigLabelHelp {
            get {
                return ResourceManager.GetString("ConfigLabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied To Clipboard 的本地化字符串。
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied 的本地化字符串。
        /// </summary>
        internal static string CopyTransactionsHelp {
            get {
                return ResourceManager.GetString("CopyTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 transactions to clipboard. 的本地化字符串。
        /// </summary>
        internal static string CopyTransactionsHelp1 {
            get {
                return ResourceManager.GetString("CopyTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Settings 的本地化字符串。
        /// </summary>
        internal static string Current_Settings {
            get {
                return ResourceManager.GetString("Current Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Settings 的本地化字符串。
        /// </summary>
        internal static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note:
        ///1. The 3 preset currencies cannot be deleted, you can only hide them.
        ///2. Not recommend to track not-currency items, there should be another plugin to do that.
        ///(If you insist, that&apos;s also ok)
        ///3. Deleting currencies will not delete the existing data files, if necessary, please delete them yourself. 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to Add: the currency you selected has already existed 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp1 {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to Delete: the currency you selected does not exist 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyHelp2 {
            get {
                return ResourceManager.GetString("CustomCurrencyHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Currency Tracker 的本地化字符串。
        /// </summary>
        internal static string CustomCurrencyTracker {
            get {
                return ResourceManager.GetString("CustomCurrencyTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete  的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Di {
            get {
                return ResourceManager.GetString("Di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Unit: Billion) 的本地化字符串。
        /// </summary>
        internal static string DividedUnitBil {
            get {
                return ResourceManager.GetString("DividedUnitBil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Unit: Million) 的本地化字符串。
        /// </summary>
        internal static string DividedUnitMil {
            get {
                return ResourceManager.GetString("DividedUnitMil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Unit: Thousand) 的本地化字符串。
        /// </summary>
        internal static string DividedUnitThou {
            get {
                return ResourceManager.GetString("DividedUnitThou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press Enter to Confirm 的本地化字符串。
        /// </summary>
        internal static string EditHelp {
            get {
                return ResourceManager.GetString("EditHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a location name. 的本地化字符串。
        /// </summary>
        internal static string EditHelp1 {
            get {
                return ResourceManager.GetString("EditHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changed 的本地化字符串。
        /// </summary>
        internal static string EditHelp2 {
            get {
                return ResourceManager.GetString("EditHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 transactions&apos; Location to: 的本地化字符串。
        /// </summary>
        internal static string EditHelp3 {
            get {
                return ResourceManager.GetString("EditHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Date 的本地化字符串。
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export .CSV 的本地化字符串。
        /// </summary>
        internal static string ExportCsv {
            get {
                return ResourceManager.GetString("ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No transactions under the currently selected currency. 的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage1 {
            get {
                return ResourceManager.GetString("ExportCsvMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time,Amount,Change,Location 的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage2 {
            get {
                return ResourceManager.GetString("ExportCsvMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A .csv file has been exported to:  的本地化字符串。
        /// </summary>
        internal static string ExportCsvMessage3 {
            get {
                return ResourceManager.GetString("ExportCsvMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note 1: To avoid errors, please do not enter a file name that is &quot;too long&quot;
        ///Note 2: The exported transactions will be subject to all the sorting and filtering conditions that are currently enabled (excluding paging). 的本地化字符串。
        /// </summary>
        internal static string FileRenameHelp {
            get {
                return ResourceManager.GetString("FileRenameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If left blank, the file name will be: 的本地化字符串。
        /// </summary>
        internal static string FileRenameHelp1 {
            get {
                return ResourceManager.GetString("FileRenameHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a File Name: (Press Enter to Confirm) 的本地化字符串。
        /// </summary>
        internal static string FileRenameLabel {
            get {
                return ResourceManager.GetString("FileRenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename: 的本地化字符串。
        /// </summary>
        internal static string FileRenameLabel1 {
            get {
                return ResourceManager.GetString("FileRenameLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentTime 的本地化字符串。
        /// </summary>
        internal static string FileRenameLabel2 {
            get {
                return ResourceManager.GetString("FileRenameLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer Filter 的本地化字符串。
        /// </summary>
        internal static string FilterByTime {
            get {
                return ResourceManager.GetString("FilterByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Gong {
            get {
                return ResourceManager.GetString("Gong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string GraphHelpMessages {
            get {
                return ResourceManager.GetString("GraphHelpMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -Suggest enabling filters on the main window to reduce the number of transactions shown here.
        ///-You can adjust a plot by clicking on the horizontal or vertical axis.
        ///-This window is still in testing. If you encounter any bugs or have ideas for new features, please submit an issue on my Github page. 的本地化字符串。
        /// </summary>
        internal static string GraphHelpMessages1 {
            get {
                return ResourceManager.GetString("GraphHelpMessages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transactions Amount: 的本地化字符串。
        /// </summary>
        internal static string GraphLabel {
            get {
                return ResourceManager.GetString("GraphLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphs 的本地化字符串。
        /// </summary>
        internal static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Above 的本地化字符串。
        /// </summary>
        internal static string Greater {
            get {
                return ResourceManager.GetString("Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide
        ///(Double Right-Click) 的本地化字符串。
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inverse Select 的本地化字符串。
        /// </summary>
        internal static string InverseSelect {
            get {
                return ResourceManager.GetString("InverseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Below 的本地化字符串。
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location Change Graph 的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph {
            get {
                return ResourceManager.GetString("LocationAmountGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [Location - Change] 的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph1 {
            get {
                return ResourceManager.GetString("LocationAmountGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * This plot mainly reflects the the total amount of Change of each location in the currency transactions. 的本地化字符串。
        /// </summary>
        internal static string LocationAmountGraph2 {
            get {
                return ResourceManager.GetString("LocationAmountGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location Filter 的本地化字符串。
        /// </summary>
        internal static string LocationFilter {
            get {
                return ResourceManager.GetString("LocationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location Graph 的本地化字符串。
        /// </summary>
        internal static string LocationGraph {
            get {
                return ResourceManager.GetString("LocationGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [Location - Frequency] 的本地化字符串。
        /// </summary>
        internal static string LocationGraph1 {
            get {
                return ResourceManager.GetString("LocationGraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * This plot mainly reflects the frequency of occurrence of each location in the currency transactions. 的本地化字符串。
        /// </summary>
        internal static string LocationGraph2 {
            get {
                return ResourceManager.GetString("LocationGraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage 的本地化字符串。
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge 的本地化字符串。
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a threshold 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merged  的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp1 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  transactions. 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp2 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge transactions under the currently selected currency with the same location, adjacent to each other, and with a Change &lt; threshold.
        ///After merging, the Time and Amount of the merged record will be taken from the latest record among the merged ones, while the Change will be summed up.
        ///If the threshold is 0, the plugin will merge ALL transactions under the currently selected currency with the same location, adjacent to each other.
        ///
        ///One-Way Merge: Transactions with Changes in positive and negative are s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp3 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select at least 2 transactions. 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsHelp4 {
            get {
                return ResourceManager.GetString("MergeTransactionsHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Merge 的本地化字符串。
        /// </summary>
        internal static string MergeTransactionsLabel4 {
            get {
                return ResourceManager.GetString("MergeTransactionsLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Value 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValue {
            get {
                return ResourceManager.GetString("MinimumRecordValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Duty:
        ///Only make a new transaction when absolute Change is ≥ 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out of Duty:
        ///Only make a new transaction when absolute Change is ≥ 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp1 {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Note:
        ///1.May cause inaccurate location recording, based on the value you set.
        ///2.When leave a duty zone, a new transaction will be made regardless of whether current Change reaches the threshold.
        ///   So if you just want &quot;One Duty, One Transaction&quot;, you could just set the In Duty value to a high one (like 100k for Gil etc.) 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueHelp2 {
            get {
                return ResourceManager.GetString("MinimumRecordValueHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Duty: 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out of Duty: 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel1 {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string MinimumRecordValueLabel2 {
            get {
                return ResourceManager.GetString("MinimumRecordValueLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M 的本地化字符串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Negative 的本地化字符串。
        /// </summary>
        internal static string NegativeChange {
            get {
                return ResourceManager.GetString("NegativeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No transactions currently selected. 的本地化字符串。
        /// </summary>
        internal static string NoTransactionsSelected {
            get {
                return ResourceManager.GetString("NoTransactionsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now 的本地化字符串。
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One-Way Merge 的本地化字符串。
        /// </summary>
        internal static string OneWayMerge {
            get {
                return ResourceManager.GetString("OneWayMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Folder 的本地化字符串。
        /// </summary>
        internal static string OpenDataFolder {
            get {
                return ResourceManager.GetString("OpenDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All hidden currencies have been restored! 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp {
            get {
                return ResourceManager.GetString("OrderChangeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restored 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp1 {
            get {
                return ResourceManager.GetString("OrderChangeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 currencies. 的本地化字符串。
        /// </summary>
        internal static string OrderChangeHelp2 {
            get {
                return ResourceManager.GetString("OrderChangeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Order: 的本地化字符串。
        /// </summary>
        internal static string OrderChangeLabel {
            get {
                return ResourceManager.GetString("OrderChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search... 的本地化字符串。
        /// </summary>
        internal static string PleaseSearch {
            get {
                return ResourceManager.GetString("PleaseSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select... 的本地化字符串。
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Positive 的本地化字符串。
        /// </summary>
        internal static string PositiveChange {
            get {
                return ResourceManager.GetString("PositiveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Hidden
        ///(Double Right-Click) 的本地化字符串。
        /// </summary>
        internal static string RestoreHidden {
            get {
                return ResourceManager.GetString("RestoreHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inverse Sort 的本地化字符串。
        /// </summary>
        internal static string ReverseSort {
            get {
                return ResourceManager.GetString("ReverseSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Date 的本地化字符串。
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Threshold 的本地化字符串。
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track in Duty 的本地化字符串。
        /// </summary>
        internal static string TrackInDuty {
            get {
                return ResourceManager.GetString("TrackInDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you left this unchecked, the plugin will pause recording any Changes when you are in Duty until left, which will also result in recording inaccurate Location.
        ///
        ///It is recommended to configure Min Value simultaneously. 的本地化字符串。
        /// </summary>
        internal static string TrackInDutyHelp {
            get {
                return ResourceManager.GetString("TrackInDutyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer Mode:
        ///Check all currency changes every 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp {
            get {
                return ResourceManager.GetString("TrackModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 milliseconds 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp1 {
            get {
                return ResourceManager.GetString("TrackModeHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Mode:
        ///Check all currency changes whenever a new chat message from specific types is received
        ///(May record more accurate transactions data)
        ///
        ///Note: If you found the plugin didn&apos;t record the change under certain circumstances, please report it with the situation! 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp2 {
            get {
                return ResourceManager.GetString("TrackModeHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too low trigger interval may result in higher performance overhead (not significant) 的本地化字符串。
        /// </summary>
        internal static string TrackModeHelp3 {
            get {
                return ResourceManager.GetString("TrackModeHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track Mode 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel {
            get {
                return ResourceManager.GetString("TrackModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer Mode 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel1 {
            get {
                return ResourceManager.GetString("TrackModeLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Mode 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel2 {
            get {
                return ResourceManager.GetString("TrackModeLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval (ms) 的本地化字符串。
        /// </summary>
        internal static string TrackModeLabel3 {
            get {
                return ResourceManager.GetString("TrackModeLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transactions 的本地化字符串。
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching transactions found. 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp {
            get {
                return ResourceManager.GetString("TransactionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No currency being selected now. 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp1 {
            get {
                return ResourceManager.GetString("TransactionsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: The operation cannot be rolled back. If necessary, please make a backup 的本地化字符串。
        /// </summary>
        internal static string TransactionsHelp2 {
            get {
                return ResourceManager.GetString("TransactionsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Records Per Page: 的本地化字符串。
        /// </summary>
        internal static string TransactionsPerPage {
            get {
                return ResourceManager.GetString("TransactionsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two-Way Merge 的本地化字符串。
        /// </summary>
        internal static string TwoWayMerge {
            get {
                return ResourceManager.GetString("TwoWayMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Currency 的本地化字符串。
        /// </summary>
        internal static string UnknownCurrency {
            get {
                return ResourceManager.GetString("UnknownCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string UnknownLocation {
            get {
                return ResourceManager.GetString("UnknownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unselect 的本地化字符串。
        /// </summary>
        internal static string Unselect {
            get {
                return ResourceManager.GetString("Unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sun, Mon, Tue, Wed, Thu, Fri, Sat 的本地化字符串。
        /// </summary>
        internal static string WeekDays {
            get {
                return ResourceManager.GetString("WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y 的本地化字符串。
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
