<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Dalamud.CN.NET.Sdk/14.0.2">
    <PropertyGroup>
        <Title>Currency Tracker</Title>
        <Description>To tracks your all currencies</Description>
        <Authors>AtmoOmen</Authors>
        <Version>1.6.5.0</Version>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    </PropertyGroup>

    <PropertyGroup>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>true</ImplicitUsings>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <BaseOutputPath>$(SolutionDir)bin</BaseOutputPath>
        <SatelliteResourceLanguages>xxx</SatelliteResourceLanguages>
        <NoWarn>1701;1702;CS0414;CS8601;CS8602;CS8604;CS8603;IDE1006;IDE0300;MSB3270;MSB324;CS0649;CA2211;CS8509;CS8625;MSB3305;CS8618;CS8600;CS8605;CS8620</NoWarn>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <Optimize>True</Optimize>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\Assets\icon.png" CopyToOutputDirectory="Always" Link="images\icon.png" />
        <None Include="Manager\Langs\*.resx" CopyToOutputDirectory="Always"/>
        <None Include="CurrencyTracker.json" CopyToOutputDirectory="Always"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="IntervalUtility" Version="1.0.0"/>
        <PackageReference Include="TinyPinyin" Version="1.1.0"/>

        <ProjectReference Include="..\OmenTools\OmenTools.csproj"/>
    </ItemGroup>

</Project>
